Repository XavierGuertin/CondoVision, pull requests merged in 2024-03, with the labels that each got.

#23 CV-31--Added UserProfile page
  apps/native/App.tsx
  apps/native/assets/profilepicture.png
  apps/native/screens/LoginScreen.tsx
  apps/native/screens/UserProfile.tsx
  apps/native/screens/index.tsx
  package-lock.json
  package.json
Labels: Sprint 2

#45 Registration Key function
  apps/native/App.tsx
  apps/native/components/CondoUnitRegistrationComponent.tsx
  apps/native/components/PropertyProfileComponent.tsx
  apps/native/components/UserPropertyForm.tsx
  apps/native/package.json
  apps/native/screens/CondoUnitRegistrationScreen.tsx
  apps/native/screens/PropertyManagementScreen.tsx
  package-lock.json
  package.json
Labels: Sprint 3

#44 PDF File Upload for Created Properties
  apps/native/components/AddCondoUnitInformation.tsx
  apps/native/components/PDFUploader.tsx
  apps/native/components/PropertyProfileComponent.tsx
  apps/native/package.json
  package-lock.json
  package.json
Labels: enhancement

#50 WEB - Notification Center
  apps/native/.gitignore
  apps/web/app/index.css
  packages/ui/src/CondoProfileComponent.tsx
  packages/ui/src/DashboardNav.tsx
  packages/ui/src/NotificationsModal.tsx
  packages/ui/src/UserProfileModal.tsx
Labels: enhancement, Sprint 3

#48 [WEB] GD-PropertiesList
  apps/native/components/CondoUnitAdapter.tsx
  apps/web/app/dashboard/page.tsx
  apps/web/app/properties/page.tsx
  packages/ui/src/constants/index.tsx
  packages/ui/src/dashboard/DashboardCard.tsx
  packages/ui/src/finance/DefaultFinanceCard.tsx
  packages/ui/src/index.tsx
  packages/ui/src/properties/PropertyComponent.tsx
  packages/ui/src/properties/PropertyList.tsx
  public/images/propertiesImage.jpg
Labels: enhancement, Sprint 3

#52 Payment Fee Status and History Screen
  apps/native/App.tsx
  apps/native/screens/CondoPaymentFeeStatusAndHistoryScreen.tsx
  apps/native/screens/CondoUnitDescriptionScreen.tsx
  apps/native/screens/index.tsx
Labels: enhancement, Sprint 3

#54 Fixed existing unit tests
  apps/native/components/AddCondoProfileProperty.tsx
  apps/native/components/AddCondoUnitInformation.tsx
  apps/native/cypress/e2e/userprofile.cy.ts
  apps/native/screens/UserProfileScreen.tsx
Labels: Sprint 3, refactoring

#62 Added the facility reservation feature
  apps/native/App.tsx
  apps/native/components/AddFacilities.tsx
  apps/native/components/PropertyProfileComponent.tsx
  apps/native/package.json
  apps/native/screens/FacilityBookingScreen.tsx
  apps/native/screens/index.tsx
  package-lock.json
Labels: enhancement, Sprint 3

#64 [FEATURE]: Implement CondoFeeCalculationScreen in CondoUnitDescriptionScreen
  apps/native/App.tsx
  apps/native/cypress/e2e/CondoFeeCalculationScreen.cy.ts
  apps/native/screens/CondoFeeCalculationScreen.tsx
  apps/native/screens/CondoUnitDescriptionScreen.tsx
  apps/native/screens/ReportScreen.tsx
  apps/native/screens/index.tsx
Labels: enhancement, Sprint 3

#68 [WEB] Condo management companies can create a profile for a property under their management
  apps/web/app/properties/page.tsx
  apps/web/cypress/e2e/properties/propertyCreation.cy.ts
  packages/ui/src/index.tsx
  packages/ui/src/properties/CreatePropertyModal.tsx
  packages/ui/src/properties/CreateUnitModal.tsx
  packages/ui/src/properties/PropertyList.tsx
Labels: enhancement, Sprint 4
