Repository XavierGuertin/CondoVision, pull requests merged in 2024-04, with the labels that each got.

#70 [86aztjcv3] Added New Field "isPayed" When Condo is Created
  apps/native/components/AddCondoUnitInformation.tsx
Labels: enhancement, refactoring, Sprint 4

#69 [86azrkcgh] Refactored userprofile unit test to run faster
  apps/native/cypress/e2e/userprofile.cy.ts
Labels: refactoring, Sprint 4

#71 [CV-406] [Web] Users can reserve common facilities
  apps/web/app/properties/page.tsx
  apps/web/cypress/e2e/properties/facilityBooking.cy.ts
  package-lock.json
  package.json
  packages/ui/src/index.tsx
  packages/ui/src/properties/FacilityBookingPage.tsx
  packages/ui/src/properties/PropertyComponent.tsx
Labels: enhancement, Sprint 4

#73 [CV-415] Implement Add Facility Modal in Property Management UI
  packages/ui/src/properties/AddFacilitiesModal.tsx
  packages/ui/src/properties/PropertyComponent.tsx
Labels: Sprint 4

#75 [CV-421] Added Financial Status to Web
  apps/native/components/CondoUnitAdapter.tsx
  apps/native/screens/PropertyManagementScreen.tsx
  apps/web/app/properties/page.tsx
  packages/ui/src/finance/DefaultFinanceCard.tsx
  packages/ui/src/properties/PropertyComponent.tsx
  packages/ui/src/properties/PropertyList.tsx
Labels: enhancement, Sprint 4

#76 [CV-429] Dynamic user condo unit display
  apps/native/components/CondoUnitRegistrationComponent.tsx
  apps/native/components/PropertyProfileComponent.tsx
  apps/native/components/UserCondoUnitsList.tsx
  apps/native/components/UserPropertyForm.tsx
  apps/native/screens/CondoUnitDescriptionScreen.tsx
  apps/native/screens/CondoUnitRegistrationScreen.tsx
Labels: enhancement, Sprint 4

#22 [CV-407] Lv Owner Map Screen
  .gitignore
  apps/native/App.tsx
  apps/native/components/AddCondoProfileProperty.tsx
  apps/native/components/MapComponent.tsx
  apps/native/components/MapComponent.web.tsx
  apps/native/components/PropertyAdapter.tsx
  apps/native/cypress/e2e/MapScreen.cy.ts
  apps/native/screens/MapScreen.tsx
  apps/native/screens/PropertyManagementScreen.tsx
  apps/native/screens/index.tsx
  apps/web/app/properties/page.tsx
  package-lock.json
  package.json
  packages/ui/src/properties/CreatePropertyModal.tsx
Labels: enhancement, Sprint 4

#79 [CV-413][Web] Condo management companies can set up different roles for different employees
  apps/web/cypress/e2e/properties/addingemployee.cy.ts
  packages/ui/src/properties/AddEmployeeModalWeb.tsx
  packages/ui/src/properties/EmployeeListModalWeb.tsx
  packages/ui/src/properties/PropertyComponent.tsx
Labels: enhancement, Sprint 4

#82 Display Registration Key
  apps/native/components/UserPropertyForm.tsx
Labels: enhancement

#83 [CV-420][Web] Condo Fee Calculation
  apps/web/app/properties/page.tsx
  packages/ui/src/DashboardNav.tsx
  packages/ui/src/finance/DefaultCondoFeeCalcCard.tsx
  packages/ui/src/index.tsx
  packages/ui/src/properties/PropertyComponent.tsx
  packages/ui/src/properties/PropertyList.tsx
Labels: enhancement
